osx:
  build: .
  volumes:
    - ./dist:/src/repackager/dist
    - /src/repackager/cache
  environment:
    PLATFORM: darwin
    ARCH: x64

linux_x64:
  build: .
  volumes:
    - ./dist:/src/repackager/dist
    - /src/repackager/cache
  environment:
    PLATFORM: linux
    ARCH: x64

linux_ia32:
  build: .
  volumes:
    - ./dist:/src/repackager/dist
    - /src/repackager/cache
  environment:
    PLATFORM: linux
    ARCH: ia32
